# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import geoip_pb2 as geoip__pb2


class GeoIpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getCountry = channel.unary_unary(
                '/GeoIpService/getCountry',
                request_serializer=geoip__pb2.GeoIpRequest.SerializeToString,
                response_deserializer=geoip__pb2.GeoIpResponse.FromString,
                )


class GeoIpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getCountry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeoIpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getCountry': grpc.unary_unary_rpc_method_handler(
                    servicer.getCountry,
                    request_deserializer=geoip__pb2.GeoIpRequest.FromString,
                    response_serializer=geoip__pb2.GeoIpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GeoIpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeoIpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getCountry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GeoIpService/getCountry',
            geoip__pb2.GeoIpRequest.SerializeToString,
            geoip__pb2.GeoIpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
