# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geoip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='geoip.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgeoip.proto\"\x1a\n\x0cGeoIpRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"_\n\rGeoIpResponse\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\x02\x12\x11\n\tlongitude\x18\x05 \x01(\x02\x32:\n\x0cGeoIpService\x12*\n\x07getCity\x12\r.GeoIpRequest\x1a\x0e.GeoIpResponse\"\x00\x62\x06proto3'
)




_GEOIPREQUEST = _descriptor.Descriptor(
  name='GeoIpRequest',
  full_name='GeoIpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='GeoIpRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=41,
)


_GEOIPRESPONSE = _descriptor.Descriptor(
  name='GeoIpResponse',
  full_name='GeoIpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='GeoIpResponse.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country', full_name='GeoIpResponse.country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city', full_name='GeoIpResponse.city', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='GeoIpResponse.latitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='GeoIpResponse.longitude', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['GeoIpRequest'] = _GEOIPREQUEST
DESCRIPTOR.message_types_by_name['GeoIpResponse'] = _GEOIPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoIpRequest = _reflection.GeneratedProtocolMessageType('GeoIpRequest', (_message.Message,), {
  'DESCRIPTOR' : _GEOIPREQUEST,
  '__module__' : 'geoip_pb2'
  # @@protoc_insertion_point(class_scope:GeoIpRequest)
  })
_sym_db.RegisterMessage(GeoIpRequest)

GeoIpResponse = _reflection.GeneratedProtocolMessageType('GeoIpResponse', (_message.Message,), {
  'DESCRIPTOR' : _GEOIPRESPONSE,
  '__module__' : 'geoip_pb2'
  # @@protoc_insertion_point(class_scope:GeoIpResponse)
  })
_sym_db.RegisterMessage(GeoIpResponse)



_GEOIPSERVICE = _descriptor.ServiceDescriptor(
  name='GeoIpService',
  full_name='GeoIpService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=140,
  serialized_end=198,
  methods=[
  _descriptor.MethodDescriptor(
    name='getCity',
    full_name='GeoIpService.getCity',
    index=0,
    containing_service=None,
    input_type=_GEOIPREQUEST,
    output_type=_GEOIPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GEOIPSERVICE)

DESCRIPTOR.services_by_name['GeoIpService'] = _GEOIPSERVICE

# @@protoc_insertion_point(module_scope)
